$axure.loadCurrentPage({
  "url":"安全设置-密码.html",
  "generationDate":new Date(1592623290306),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e3625e9381fd43298c48aed0423daa7d",
    "type":"Axure:Page",
    "name":"安全设置-密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2086046aa7634c0b860fed4a31521397",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":0},
            "size":{
              "width":647,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad983ef66214c779733d4328f7e5813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":647,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安全设置-密码/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2086046aa7634c0b860fed4a31521397":{
      "scriptId":"u0"},
    "fad983ef66214c779733d4328f7e5813":{
      "scriptId":"u1"}}});