$axure.loadCurrentPage({
  "url":"__-home.html",
  "generationDate":new Date(1592623290327),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ed8ddef094cc401798320f414e1eb178",
    "type":"Axure:Page",
    "name":"概述-home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e3bfde3a587248beb0b8f230cb3c6f43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1390,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02fb456a52f24b4fb7bbd7f494bd6b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1390,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__-home/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e3bfde3a587248beb0b8f230cb3c6f43":{
      "scriptId":"u0"},
    "02fb456a52f24b4fb7bbd7f494bd6b9f":{
      "scriptId":"u1"}}});