$axure.loadCurrentPage({
  "url":"添加文章.html",
  "generationDate":new Date(1592623290189),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"486e8da479f545ac94a35d569c5500de",
    "type":"Axure:Page",
    "name":"添加文章",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aeb2a5d44c9f4ac380ba1863f3ddc3e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":10},
            "size":{
              "width":746,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb68c34d1d3a44f896c238316077f1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":10},
                "size":{
                  "width":746,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加文章/u0.png"}},
{
          "id":"c4731e2612824fc1ae53468313e67a60",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":430},
            "size":{
              "width":616,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74c12cb40e3d45609553880972b7841f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":430},
                "size":{
                  "width":616,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加文章/u2.png"}},
{
          "id":"da8456f508c64eb48c06bcb0fdbcef1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":19,
              "y":60},
            "size":{
              "width":301,
              "height":418}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a4d80a5582849ca87408a44d003e93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":19,
                  "y":60},
                "size":{
                  "width":301,
                  "height":418}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "aeb2a5d44c9f4ac380ba1863f3ddc3e2":{
      "scriptId":"u0"},
    "eb68c34d1d3a44f896c238316077f1df":{
      "scriptId":"u1"},
    "c4731e2612824fc1ae53468313e67a60":{
      "scriptId":"u2"},
    "74c12cb40e3d45609553880972b7841f":{
      "scriptId":"u3"},
    "da8456f508c64eb48c06bcb0fdbcef1e":{
      "scriptId":"u4"},
    "8a4d80a5582849ca87408a44d003e93a":{
      "scriptId":"u5"}}});