$axure.loadCurrentPage({
  "url":"____-column-list.html",
  "generationDate":new Date(1592623290561),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a661ba7ea80d4f5abe7ba24280f00a31",
    "type":"Axure:Page",
    "name":"专栏列表-column-list",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62d853d703f4433fb8a154837ba408e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1210,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f59aec8b7a04e048901b4fdd73dc9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1210,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-column-list/u0.png"}},
{
          "id":"ef4c4ad4284d4fb8853f984b765423c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1060,
              "y":195},
            "size":{
              "width":184,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f486c6b67684339805700abc6857349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1060,
                  "y":195},
                "size":{
                  "width":184,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca1de6ab640c4510845988752231bade",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":130,
              "y":10},
            "size":{
              "width":398,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c940adf534c9433680ed08a9adee0423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":10},
                "size":{
                  "width":398,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "62d853d703f4433fb8a154837ba408e7":{
      "scriptId":"u0"},
    "4f59aec8b7a04e048901b4fdd73dc9da":{
      "scriptId":"u1"},
    "ef4c4ad4284d4fb8853f984b765423c5":{
      "scriptId":"u2"},
    "1f486c6b67684339805700abc6857349":{
      "scriptId":"u3"},
    "ca1de6ab640c4510845988752231bade":{
      "scriptId":"u4"},
    "c940adf534c9433680ed08a9adee0423":{
      "scriptId":"u5"}}});