$axure.loadCurrentPage({
  "url":"____-category-list.html",
  "generationDate":new Date(1592623290538),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ef0e4c5ad43414db8ff887e5f999e47",
    "type":"Axure:Page",
    "name":"分类管理-category-list",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"58d75c44bdc64c7baac740067911d801",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1270,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14711b6d8ee5423893a7e0d1ec091640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1270,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-category-list/u0.png"}},
{
          "id":"f7cafe7ec0504d67b90105eec11e44dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325.000030517578,
              "y":460},
            "size":{
              "width":875,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82bcaf4919a470d9537f170f70629f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325.000030517578,
                  "y":460},
                "size":{
                  "width":875,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-category-list/u2.png"}},
{
          "id":"89aa95425b1d418d85acacf6cee8ee52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":88,
              "y":470},
            "size":{
              "width":203,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"272c9a84f42c4cb4a3b5edb0bf7660fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":88,
                  "y":470},
                "size":{
                  "width":203,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84269dd3864041d287f00e34eb7f3002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1136,
              "y":95},
            "size":{
              "width":124,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e6c238421e4984a0b6cd5556bccf36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1136,
                  "y":95},
                "size":{
                  "width":124,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c391911e5204a09bc9642f1fd5b30e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":335},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe515bc52d1464abd7d27d28057a426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":335},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "58d75c44bdc64c7baac740067911d801":{
      "scriptId":"u0"},
    "14711b6d8ee5423893a7e0d1ec091640":{
      "scriptId":"u1"},
    "f7cafe7ec0504d67b90105eec11e44dd":{
      "scriptId":"u2"},
    "e82bcaf4919a470d9537f170f70629f7":{
      "scriptId":"u3"},
    "89aa95425b1d418d85acacf6cee8ee52":{
      "scriptId":"u4"},
    "272c9a84f42c4cb4a3b5edb0bf7660fd":{
      "scriptId":"u5"},
    "84269dd3864041d287f00e34eb7f3002":{
      "scriptId":"u6"},
    "c1e6c238421e4984a0b6cd5556bccf36":{
      "scriptId":"u7"},
    "2c391911e5204a09bc9642f1fd5b30e4":{
      "scriptId":"u8"},
    "dfe515bc52d1464abd7d27d28057a426":{
      "scriptId":"u9"}}});