$axure.loadCurrentPage({
  "url":"____-question.html",
  "generationDate":new Date(1592623290373),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bd2f078e615b4f9d9ab41758f694f45f",
    "type":"Axure:Page",
    "name":"问题管理-question",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0eabf7ec1c7b4bd6877d51260f769a47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1170,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2649093f34c944549d264e5b759fa8e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1170,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-question/u0.png"}},
{
          "id":"3dc2096d842944d0b020d369d72a1bab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":535,
              "y":270},
            "size":{
              "width":635,
              "height":650}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f00ee4be0b45ab84401781424617e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":535,
                  "y":270},
                "size":{
                  "width":635,
                  "height":650}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-question/u2.png"}},
{
          "id":"c6628ed5d7c34bbab8142eebd5550bf5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":30},
            "size":{
              "width":90,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"9838262de4224009ac1fe80ea809c460",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1008,
              "y":160},
            "size":{
              "width":161,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63c74a2138a849d0971b77bb40b98c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1008,
                  "y":160},
                "size":{
                  "width":161,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d3d91d5e5f0450abe34f44697216373",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":340},
            "size":{
              "width":188,
              "height":314}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"619483fe0cbc44d9aba2511a7b77b617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":340},
                "size":{
                  "width":188,
                  "height":314}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____-question/u7.png"}},
{
          "id":"9376e0da6d7941b3b61649d94f4c4ed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":310},
            "size":{
              "width":283,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40db55ca3b47401bba7f9eb37fbffb73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":310},
                "size":{
                  "width":283,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0eabf7ec1c7b4bd6877d51260f769a47":{
      "scriptId":"u0"},
    "2649093f34c944549d264e5b759fa8e4":{
      "scriptId":"u1"},
    "3dc2096d842944d0b020d369d72a1bab":{
      "scriptId":"u2"},
    "c1f00ee4be0b45ab84401781424617e2":{
      "scriptId":"u3"},
    "c6628ed5d7c34bbab8142eebd5550bf5":{
      "scriptId":"u4"},
    "9838262de4224009ac1fe80ea809c460":{
      "scriptId":"u5"},
    "63c74a2138a849d0971b77bb40b98c09":{
      "scriptId":"u6"},
    "8d3d91d5e5f0450abe34f44697216373":{
      "scriptId":"u7"},
    "619483fe0cbc44d9aba2511a7b77b617":{
      "scriptId":"u8"},
    "9376e0da6d7941b3b61649d94f4c4ed7":{
      "scriptId":"u9"},
    "40db55ca3b47401bba7f9eb37fbffb73":{
      "scriptId":"u10"}}});