$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1592623290262),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d1e886e671ac47b6aafb612a3cb36643",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3962c3c90258429fb05487f3a7037c50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":10},
            "size":{
              "width":1303,
              "height":924}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274c977056fa414c8b88b03aea88c320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":10},
                "size":{
                  "width":1303,
                  "height":924}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.png"}},
{
          "id":"037df580933a4373ab445dc0a2bc8aba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":944},
            "size":{
              "width":529,
              "height":384}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f02c119f9fc471e926b9f78fd8b7074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":944},
                "size":{
                  "width":529,
                  "height":384}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"ac502eb8a9d84536aca4d34c95e6a551",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":18,
              "y":970},
            "size":{
              "width":241,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09728f35924247669db3c98f9866d009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":18,
                  "y":970},
                "size":{
                  "width":241,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ac1f95f03c84bb7b1a74d7879d6028a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":1328},
            "size":{
              "width":526,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3befb46c7b74642bdb13d4fbd78aa76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":1328},
                "size":{
                  "width":526,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u6.png"}},
{
          "id":"dc2b640cf3794f2987e0ab9db2e54b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":30,
              "y":1328},
            "size":{
              "width":201,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0bb4d30b3d843c9b33a1fdc13589ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":30,
                  "y":1328},
                "size":{
                  "width":201,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3962c3c90258429fb05487f3a7037c50":{
      "scriptId":"u0"},
    "274c977056fa414c8b88b03aea88c320":{
      "scriptId":"u1"},
    "037df580933a4373ab445dc0a2bc8aba":{
      "scriptId":"u2"},
    "5f02c119f9fc471e926b9f78fd8b7074":{
      "scriptId":"u3"},
    "ac502eb8a9d84536aca4d34c95e6a551":{
      "scriptId":"u4"},
    "09728f35924247669db3c98f9866d009":{
      "scriptId":"u5"},
    "3ac1f95f03c84bb7b1a74d7879d6028a":{
      "scriptId":"u6"},
    "f3befb46c7b74642bdb13d4fbd78aa76":{
      "scriptId":"u7"},
    "dc2b640cf3794f2987e0ab9db2e54b11":{
      "scriptId":"u8"},
    "e0bb4d30b3d843c9b33a1fdc13589ab2":{
      "scriptId":"u9"}}});